import type { Course } from "./types"

export const STARTER_TEMPLATE: Course[] = [
  {
    id: "c01",
    num: "01",
    tag: "cisco",
    color: "indigo",
    hours: "~6h",
    type: "CCST Ciberseguridad",
    name: "Introducción a Ciberseguridad",
    deadline: "2026-06-01",
    weeks: [
      {
        id: "c01-w1",
        label: "Week 1",
        name: "Módulo 2 — Ataques, conceptos y técnicas",
        dates: "May 12–18",
        tip: "Módulo 2 is the densest. Finishing it this week gives you breathing room.",
        items: [
          { id: "c01-w1-i1", name: "Módulo 1 — Introducción a la Ciberseguridad", sub: "✓ Completado", day: "", completed: false },
          { id: "c01-w1-i2", name: "2.1 Analizando un ciberataque", sub: "En progreso", day: "Mon–Tue", completed: false },
          { id: "c01-w1-i3", name: "2.2 Métodos de infiltración", day: "Wed–Thu", completed: false },
          { id: "c01-w1-i4", name: "2.3 Aprovechamiento de vulnerabilidades", day: "Fri", completed: false },
          { id: "c01-w1-i5", name: "2.4 El panorama de la ciberseguridad", day: "Sat", completed: false },
          { id: "c01-w1-i6", name: "2.5 Cuestionario Módulo 2", day: "Sat", completed: false, exam: true },
        ],
      },
      {
        id: "c01-w2",
        label: "Week 2",
        name: "Módulo 3 — Protegiendo sus datos",
        dates: "May 19–25",
        tip: "Usually shorter. If you finish early, start Módulo 4.",
        items: [
          { id: "c01-w2-i1", name: "Módulo 3 completo", sub: "Mon–Fri, quiz Friday", day: "Mon–Fri", completed: false },
          { id: "c01-w2-i2", name: "Cuestionario Módulo 3", day: "Fri", completed: false, exam: true },
        ],
      },
      {
        id: "c01-w3",
        label: "Week 3",
        name: "Módulos 4 & 5 + Final exam",
        dates: "May 26–Jun 1",
        tip: "Reserve Friday for review. Don't leave the exam for the last minute.",
        items: [
          { id: "c01-w3-i1", name: "Módulo 4 — Protegiendo a la organización", day: "Mon–Wed", completed: false },
          { id: "c01-w3-i2", name: "Módulo 5 — ¿Tu futuro en ciberseguridad?", sub: "Don't skip", day: "Thu", completed: false },
          { id: "c01-w3-i3", name: "Encuesta de fin de curso", day: "Fri", completed: false },
          { id: "c01-w3-i4", name: "Repaso general", day: "Fri", completed: false },
          { id: "c01-w3-i5", name: "Examen final del curso", sub: "~25–30 questions", day: "Sat", completed: false, exam: true },
        ],
      },
    ],
  },
  {
    id: "c02",
    num: "02",
    tag: "cisco",
    color: "emerald",
    hours: "~10h",
    type: "CCST Ciberseguridad",
    name: "Conceptos Básicos de Redes",
    deadline: "2026-06-14",
    weeks: [
      {
        id: "c02-w1",
        label: "Week 1",
        name: "Modules 1–4 — Fundamentos",
        dates: "May 19–25",
        tip: "Introductory week. Build vocab before diving into IP.",
        items: [
          { id: "c02-w1-i1", name: "Intro del curso", sub: "33% done", day: "Mon", completed: false },
          { id: "c02-w1-i2", name: "Módulo 1 — Comunicación en un Mundo Conectado", day: "Mon–Tue", completed: false },
          { id: "c02-w1-i3", name: "Módulo 2 — Componentes, tipos y conexiones", day: "Wed", completed: false },
          { id: "c02-w1-i4", name: "Módulo 3 — Redes inalámbricas y móviles", day: "Thu", completed: false },
          { id: "c02-w1-i5", name: "Módulo 4 — Crear una Red Doméstica", day: "Fri–Sat", completed: false },
          { id: "c02-w1-i6", name: "Examen parcial: Construir una red pequeña", day: "Sat", completed: false, exam: true },
        ],
      },
      {
        id: "c02-w2",
        label: "Week 2",
        name: "Modules 5–11 — IP ⚠️",
        dates: "May 26–Jun 1",
        tip: "⚠️ Hardest week. Don't move on if subnetting isn't clear.",
        items: [
          { id: "c02-w2-i1", name: "Módulo 5 — Principios de Comunicación", sub: "OSI/TCP-IP", day: "Mon", completed: false },
          { id: "c02-w2-i2", name: "Módulo 6 — Medios de red", day: "Mon", completed: false },
          { id: "c02-w2-i3", name: "Módulo 7 — La capa de acceso", sub: "Ethernet", day: "Tue", completed: false },
          { id: "c02-w2-i4", name: "Examen parcial: Acceso a la red", day: "Tue", completed: false, exam: true },
          { id: "c02-w2-i5", name: "Módulo 8 — IPv4", day: "Wed", completed: false },
          { id: "c02-w2-i6", name: "Módulo 9 — IPv4 y subnetting", sub: "Hardest topic", day: "Thu", completed: false },
          { id: "c02-w2-i7", name: "Módulo 10 — IPv6", day: "Fri", completed: false },
          { id: "c02-w2-i8", name: "Módulo 11 — DHCP", day: "Sat", completed: false },
          { id: "c02-w2-i9", name: "Examen parcial: Protocolo de Internet", day: "Sat", completed: false, exam: true },
        ],
      },
      {
        id: "c02-w3",
        label: "Week 3",
        name: "Modules 12–17 — Routing & Protocols",
        dates: "Jun 2–7",
        tip: "Módulo 16 has 8 subsections — give it two days.",
        items: [
          { id: "c02-w3-i1", name: "Módulo 12 — Gateway y NAT", day: "Mon", completed: false },
          { id: "c02-w3-i2", name: "Módulo 13 — ARP", day: "Mon", completed: false },
          { id: "c02-w3-i3", name: "Módulo 14 — Enrutamiento", day: "Tue", completed: false },
          { id: "c02-w3-i4", name: "Examen parcial: Comunicación entre Redes", day: "Tue", completed: false, exam: true },
          { id: "c02-w3-i5", name: "Módulo 15 — TCP y UDP", day: "Wed", completed: false },
          { id: "c02-w3-i6", name: "Módulo 16 — Servicios de Aplicación", sub: "DNS, HTTP, FTP, SSH — longest", day: "Thu–Fri", completed: false },
          { id: "c02-w3-i7", name: "Módulo 17 — Utilidades de red", sub: "ping, traceroute, ipconfig", day: "Sat", completed: false },
          { id: "c02-w3-i8", name: "Examen parcial: Protocolos", day: "Sat", completed: false, exam: true },
        ],
      },
      {
        id: "c02-w4",
        label: "Week 4",
        name: "Review + Final exam",
        dates: "Jun 8–14",
        tip: "You finish June 14 — 16 days before deadline.",
        items: [
          { id: "c02-w4-i1", name: "Repaso módulos 1–11", day: "Mon–Tue", completed: false },
          { id: "c02-w4-i2", name: "Repaso módulos 12–17", day: "Wed", completed: false },
          { id: "c02-w4-i3", name: "Examen final del curso", day: "Thu–Fri", completed: false, exam: true },
          { id: "c02-w4-i4", name: "Encuesta final", day: "Fri", completed: false },
        ],
      },
    ],
  },
  {
    id: "c04",
    num: "04",
    tag: "cisco",
    color: "orange",
    hours: "~8h",
    type: "CCST Ciberseguridad",
    name: "Seguridad de Terminales",
    deadline: "2026-06-04",
    weeks: [
      {
        id: "c04-w1",
        label: "Week 1",
        name: "Módulos 1–6 — Amenazas y redes",
        dates: "May 19–25",
        tip: "",
        items: [
          { id: "c04-w1-i1", name: "Módulo 1 — Amenazas, vulnerabilidades y ataques", day: "Mon–Tue", completed: false },
          { id: "c04-w1-i2", name: "Módulo 2 — Protección de redes", day: "Wed", completed: false },
          { id: "c04-w1-i3", name: "Módulo 3 — Ataque a los fundamentos", day: "Thu", completed: false },
          { id: "c04-w1-i4", name: "Módulo 4 — Atacando lo que hacemos", day: "Fri", completed: false },
          { id: "c04-w1-i5", name: "Módulo 5 — Comunicación inalámbrica", day: "Sat", completed: false },
          { id: "c04-w1-i6", name: "Módulo 6 — Infraestructura de seguridad", day: "Sat", completed: false },
          { id: "c04-w1-i7", name: "Examen parcial: Seguridad de la red", day: "Sat", completed: false, exam: true },
        ],
      },
      {
        id: "c04-w2",
        label: "Week 2",
        name: "Módulos 7–10 — OS & Endpoints",
        dates: "May 26–Jun 1",
        tip: "Module 8 (Linux) is the longest — don't leave it for the last day.",
        items: [
          { id: "c04-w2-i1", name: "Módulo 7 — Sistema operativo Windows", sub: "Architecture, config, security", day: "Mon–Tue", completed: false },
          { id: "c04-w2-i2", name: "Módulo 8 — Linux", sub: "Shell, servers, filesystem — 8 subsections", day: "Wed–Thu", completed: false },
          { id: "c04-w2-i3", name: "Módulo 9 — Protección de terminales", day: "Fri", completed: false },
          { id: "c04-w2-i4", name: "Módulo 10 — Principios de ciberseguridad", day: "Sat", completed: false },
          { id: "c04-w2-i5", name: "Examen parcial: SO y seguridad", day: "Sat", completed: false, exam: true },
        ],
      },
      {
        id: "c04-w3",
        label: "Week 3",
        name: "Final exam",
        dates: "Jun 2–4",
        tip: "",
        items: [
          { id: "c04-w3-i1", name: "Repaso general", day: "Mon–Tue", completed: false },
          { id: "c04-w3-i2", name: "Examen final del curso", day: "Wed", completed: false, exam: true },
          { id: "c04-w3-i3", name: "Encuesta final", day: "Wed", completed: false },
        ],
      },
    ],
  },
  {
    id: "c05",
    num: "05",
    tag: "cisco",
    color: "violet",
    hours: "~12h",
    type: "CCST Ciberseguridad",
    name: "Defensa de la Red",
    deadline: "2026-06-14",
    weeks: [
      {
        id: "c05-w1",
        label: "Week 1",
        name: "Módulos 1–3 — Defense & Access",
        dates: "May 26–Jun 1",
        tip: "Module 2 has 8 subsections — one of the longest.",
        items: [
          { id: "c05-w1-i1", name: "Intro + Packet Tracer setup", sub: "Install if you haven't", day: "Mon", completed: false },
          { id: "c05-w1-i2", name: "Módulo 1 — Comprendiendo qué es Defensa", day: "Mon–Tue", completed: false },
          { id: "c05-w1-i3", name: "Módulo 2 — Defensa del sistema y la red", sub: "8 subsections", day: "Wed–Thu", completed: false },
          { id: "c05-w1-i4", name: "Módulo 3 — Control de Acceso", sub: "AAA, accounts", day: "Fri", completed: false },
          { id: "c05-w1-i5", name: "Examen parcial: Principios de Defensa", day: "Sat", completed: false, exam: true },
        ],
      },
      {
        id: "c05-w2",
        label: "Week 2",
        name: "Módulos 4–8 — ACL, Firewalls, Cloud & Crypto",
        dates: "Jun 2–8",
        tip: "Module 8 (Cryptography) is conceptually dense — take your time with PKI.",
        items: [
          { id: "c05-w2-i1", name: "Módulo 4 — ACL", sub: "Wildcard, IPv4/IPv6", day: "Mon–Tue", completed: false },
          { id: "c05-w2-i2", name: "Módulo 5 — Firewalls", day: "Wed", completed: false },
          { id: "c05-w2-i3", name: "Módulo 6 — ZPF", sub: "Zone-based firewalls", day: "Thu", completed: false },
          { id: "c05-w2-i4", name: "Módulo 7 — Seguridad en la nube", sub: "VMs, virtualization", day: "Fri", completed: false },
          { id: "c05-w2-i5", name: "Módulo 8 — Criptografía", sub: "Hash, PKI, encryption", day: "Sat", completed: false },
          { id: "c05-w2-i6", name: "Examen parcial: Firewalls, Crypto, Cloud", day: "Sat", completed: false, exam: true },
        ],
      },
      {
        id: "c05-w3",
        label: "Week 3",
        name: "Módulos 9–11 + Final",
        dates: "Jun 9–14",
        tip: "Protect your review days — don't compress them.",
        items: [
          { id: "c05-w3-i1", name: "Módulo 9 — Tecnologías y protocolos", day: "Mon", completed: false },
          { id: "c05-w3-i2", name: "Módulo 10 — Datos de seguridad de red", day: "Tue", completed: false },
          { id: "c05-w3-i3", name: "Módulo 11 — Evaluar alertas", day: "Wed", completed: false },
          { id: "c05-w3-i4", name: "Examen parcial: Evaluación de alertas", day: "Wed", completed: false, exam: true },
          { id: "c05-w3-i5", name: "Repaso general", day: "Thu", completed: false },
          { id: "c05-w3-i6", name: "Examen final del curso", day: "Fri", completed: false, exam: true },
          { id: "c05-w3-i7", name: "Encuesta final", day: "Fri", completed: false },
        ],
      },
    ],
  },
  {
    id: "c06",
    num: "06",
    tag: "cisco",
    color: "teal",
    hours: "~6h",
    type: "CCST Ciberseguridad",
    name: "Administración de Amenazas Cibernéticas",
    deadline: "2026-06-04",
    weeks: [
      {
        id: "c06-w1",
        label: "Week 1",
        name: "Módulos 1–5 — Governance, Testing & Risk",
        dates: "May 26–Jun 1",
        tip: "More conceptual than technical — read carefully and take notes.",
        items: [
          { id: "c06-w1-i1", name: "Módulo 1 — Gestión y Cumplimiento", sub: "Governance, ethics, frameworks", day: "Mon", completed: false },
          { id: "c06-w1-i2", name: "Módulo 2 — Pruebas de Seguridad", sub: "Pen testing, tools", day: "Tue", completed: false },
          { id: "c06-w1-i3", name: "Módulo 3 — Inteligencia contra Amenazas", sub: "Sources, services", day: "Wed", completed: false },
          { id: "c06-w1-i4", name: "Módulo 4 — Evaluación de vulnerabilidades", sub: "CVSS, profiles", day: "Thu", completed: false },
          { id: "c06-w1-i5", name: "Módulo 5 — Administración de Riesgos", sub: "Risk assessment, controls", day: "Fri", completed: false },
          { id: "c06-w1-i6", name: "Examen parcial: Vulnerabilidad y Riesgos", day: "Fri", completed: false, exam: true },
        ],
      },
      {
        id: "c06-w2",
        label: "Week 2",
        name: "Módulo 6 + Final",
        dates: "Jun 2–4",
        tip: "Module 6 — Cyber Kill Chain and Diamond Model are exam favorites.",
        items: [
          { id: "c06-w2-i1", name: "Módulo 6 — Análisis Forense y Respuesta", sub: "Kill Chain, Diamond Model, IR", day: "Mon–Tue", completed: false },
          { id: "c06-w2-i2", name: "Examen parcial: Respuesta a incidentes", day: "Tue", completed: false, exam: true },
          { id: "c06-w2-i3", name: "Repaso general", day: "Wed", completed: false },
          { id: "c06-w2-i4", name: "Examen final del curso", day: "Wed", completed: false, exam: true },
          { id: "c06-w2-i5", name: "Encuesta final", day: "Wed", completed: false },
        ],
      },
    ],
  },
  {
    id: "c07",
    num: "07",
    tag: "ms",
    color: "blue",
    hours: "~5.5h",
    type: "Microsoft Learn",
    name: "Intro a Aplicaciones y Agentes de IA en Azure",
    deadline: "2026-06-03",
    weeks: [
      {
        id: "c07-w1",
        label: "Block",
        name: "6 modules — complete in 2–3 days",
        dates: "Jun 1–3",
        tip: "Each module has a ~30 min hands-on exercise in Microsoft Foundry. Needs Azure account.",
        items: [
          { id: "c07-w1-i1", name: "Intro a la IA en Azure", sub: "56 min", day: "Day 1", completed: false },
          { id: "c07-w1-i2", name: "IA Generativa y Agentes", sub: "58 min", day: "Day 1", completed: false },
          { id: "c07-w1-i3", name: "Análisis de texto", sub: "45 min", day: "Day 2", completed: false },
          { id: "c07-w1-i4", name: "Servicios de voz", sub: "47 min", day: "Day 2", completed: false },
          { id: "c07-w1-i5", name: "Computer Vision", sub: "50 min", day: "Day 3", completed: false },
          { id: "c07-w1-i6", name: "Extracción de información", sub: "43 min", day: "Day 3", completed: false },
        ],
      },
    ],
  },
  {
    id: "c08",
    num: "08",
    tag: "ms",
    color: "pink",
    hours: "~3.3h",
    type: "Microsoft Learn",
    name: "Conceptos de IA para Desarrolladores",
    deadline: "2026-05-20",
    weeks: [
      {
        id: "c08-w1",
        label: "Block",
        name: "6 modules — complete in 1–2 days",
        dates: "May 19–20",
        tip: "Shortest course (~3h). Start here to build momentum.",
        items: [
          { id: "c08-w1-i1", name: "Introducción a los conceptos de IA", sub: "40 min", day: "Day 1", completed: false },
          { id: "c08-w1-i2", name: "Intro a IA generativa y agentes", sub: "37 min", day: "Day 1", completed: false },
          { id: "c08-w1-i3", name: "Conceptos de NLP", sub: "30 min", day: "Day 1", completed: false },
          { id: "c08-w1-i4", name: "Conceptos de voz", sub: "28 min", day: "Day 2", completed: false },
          { id: "c08-w1-i5", name: "Conceptos de Computer Vision", sub: "34 min", day: "Day 2", completed: false },
          { id: "c08-w1-i6", name: "Extracción de información", sub: "28 min", day: "Day 2", completed: false },
        ],
      },
    ],
  },
  {
    id: "c09",
    num: "09",
    tag: "ms",
    color: "amber",
    hours: "~5.5h",
    type: "Microsoft Learn · AZ-900",
    name: "Introducción a la Infraestructura en la Nube",
    deadline: "2026-05-24",
    weeks: [
      {
        id: "c09-w1",
        label: "Part 1",
        name: "Cloud concepts (~1h)",
        dates: "May 21",
        tip: "",
        items: [
          { id: "c09-w1-i1", name: "Descripción de la informática en la nube", sub: "1/8 units done", completed: false },
          { id: "c09-w1-i2", name: "Ventajas de servicios en la nube", completed: false },
          { id: "c09-w1-i3", name: "Tipos de servicio en la nube", sub: "IaaS, PaaS, SaaS", completed: false },
        ],
      },
      {
        id: "c09-w2",
        label: "Part 2",
        name: "Architecture & services (~3h)",
        dates: "May 22–23",
        tip: "Identity & security connects directly to your CCST courses.",
        items: [
          { id: "c09-w2-i1", name: "Componentes arquitectónicos de Azure", completed: false },
          { id: "c09-w2-i2", name: "Servicios de proceso", sub: "VMs, containers, Functions", completed: false },
          { id: "c09-w2-i3", name: "Servicios de red", sub: "VNet, VPN, DNS", completed: false },
          { id: "c09-w2-i4", name: "Servicios de almacenamiento", completed: false },
          { id: "c09-w2-i5", name: "Identidad, acceso y seguridad", sub: "AAD, RBAC, Zero Trust", completed: false },
        ],
      },
      {
        id: "c09-w3",
        label: "Part 3",
        name: "Management & governance (~1.5h)",
        dates: "May 24",
        tip: "",
        items: [
          { id: "c09-w3-i1", name: "Administración de costos", completed: false },
          { id: "c09-w3-i2", name: "Gobernanza y cumplimiento", completed: false },
          { id: "c09-w3-i3", name: "Administrar e implementar recursos", completed: false },
          { id: "c09-w3-i4", name: "Herramientas de supervisión", completed: false },
        ],
      },
    ],
  },
  {
    id: "c10",
    num: "10",
    tag: "ms",
    color: "rose",
    hours: "~6h",
    type: "Microsoft Learn · DP-900",
    name: "Introducción a los Datos de Microsoft Azure",
    deadline: "2026-05-28",
    weeks: [
      {
        id: "c10-w1",
        label: "Part 1",
        name: "Core data concepts",
        dates: "May 25",
        tip: "",
        items: [
          { id: "c10-w1-i1", name: "Conceptos de datos principales", sub: "2/8 units done", completed: false },
          { id: "c10-w1-i2", name: "Roles y servicios de datos", completed: false },
        ],
      },
      {
        id: "c10-w2",
        label: "Part 2",
        name: "Relational data",
        dates: "May 26",
        tip: "",
        items: [
          { id: "c10-w2-i1", name: "Fundamentos de datos relacionales", sub: "SQL, normalization", completed: false },
          { id: "c10-w2-i2", name: "Servicios de BD relacionales", sub: "Azure SQL, MySQL, PostgreSQL", completed: false },
        ],
      },
      {
        id: "c10-w3",
        label: "Part 3",
        name: "Non-relational data",
        dates: "May 27",
        tip: "",
        items: [
          { id: "c10-w3-i1", name: "Azure Storage para datos no relacionales", sub: "Blob, Data Lake, Tables", completed: false },
          { id: "c10-w3-i2", name: "Azure Cosmos DB", sub: "APIs, global scale", completed: false },
        ],
      },
      {
        id: "c10-w4",
        label: "Part 4",
        name: "Data analytics",
        dates: "May 28",
        tip: "Most hands-on part — includes Fabric and Power BI exercises.",
        items: [
          { id: "c10-w4-i1", name: "Análisis a gran escala", sub: "Data warehouse, Fabric", completed: false },
          { id: "c10-w4-i2", name: "Análisis en tiempo real", sub: "Streaming, Spark", completed: false },
          { id: "c10-w4-i3", name: "Visualización de datos", sub: "Power BI", completed: false },
        ],
      },
    ],
  },
]
